version = 1

[[annotations]]
path = [
    ".astro/*",
    ".editorconfig",
    ".github/**/*",
    ".gitignore",
    "REUSE.toml",
    "astro.config.mjs",
    "bun.lock",
    "package-lock.json",
    "package.json",
    "tsconfig.json",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "public/images/icons/**",
    "public/images/noise.png",
]
SPDX-FileCopyrightText = "© Vlad-Stefan Harbuz"
SPDX-License-Identifier = "LicenseRef-Restricted"

[[annotations]]
path = [
    "public/images/branches.svg",
    "public/images/logo/**/*",
]
SPDX-FileCopyrightText = "© Open Source Endowment Foundation"
SPDX-License-Identifier = "LicenseRef-Restricted"

[[annotations]]
path = [
    "public/fonts/raleway*",
]
SPDX-FileCopyrightText = "Copyright The Raleway Project Authors (https://fonts.google.com/specimen/Raleway/license), with Reserved Font Name “Raleway”"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = [
    "public/fonts/noto-serif*",
]
SPDX-FileCopyrightText = "Copyright The Noto Project Authors (https://fonts.google.com/noto/specimen/Noto+Serif/license)"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = [
    "public/fonts/lora*",
]
SPDX-FileCopyrightText = "Copyright The Lora Project Authors (https://fonts.google.com/specimen/Lora/license), with Reserved Font Name “Lora”."
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = [
    "public/fonts/valkyrie*",
]
SPDX-FileCopyrightText = "© Matthew Butterick"
SPDX-License-Identifier = "LicenseRef-Restricted"

[[annotations]]
path = [
    "public/fonts/Geist*",
]
SPDX-FileCopyrightText = "Copyright The Geist Project Authors (https://vercel.com/font)"
SPDX-License-Identifier = "OFL-1.1"
